### PR TITLE
[WIP] Add non-container formats flac and wav

### PR DESCRIPTION
**Pull request by MKO1640**
currently not yet tested

### CODE REVIEW

**Comment by amotl** [comment]
Hi there,

thanks a stack for this contribution. Can we keep "SARASWATI_CONTAINER_FORMAT" as is and additionally add another parameter beforehand, called "SARASWATI_AUDIO_FORMAT"?

In this manner, we don't have to juggle and mess two different bits of information into the same option slot.

With kind regards,
Andreas.

On 22 July 2021 00:45:59 CEST, MKO1640 ***@***.***> wrote:
>currently not yet tested
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/hiveeyes/saraswati/pull/14
>
>-- Commit Summary --
>
>  * makeshift add non container formats flac and wav.
>
>-- File Changes --
>
>    M CHANGES.rst (2)
>    M saraswati/cli.py (14)
>    M saraswati/model.py (2)
>    M saraswati/recorder.py (24)
>    M saraswati/setup/systemd/saraswati.default (6)
>
>-- Patch Links --
>
>https://github.com/hiveeyes/saraswati/pull/14.patch
>https://github.com/hiveeyes/saraswati/pull/14.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hiveeyes/saraswati/pull/14

-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

**Comment by amotl** [comment]
Just let me know if you still have time to implement my suggestion or if you would like to see myself taking over.

On 22 July 2021 00:45:59 CEST, MKO1640 ***@***.***> wrote:
>currently not yet tested
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/hiveeyes/saraswati/pull/14
>
>-- Commit Summary --
>
>  * makeshift add non container formats flac and wav.
>
>-- File Changes --
>
>    M CHANGES.rst (2)
>    M saraswati/cli.py (14)
>    M saraswati/model.py (2)
>    M saraswati/recorder.py (24)
>    M saraswati/setup/systemd/saraswati.default (6)
>
>-- Patch Links --
>
>https://github.com/hiveeyes/saraswati/pull/14.patch
>https://github.com/hiveeyes/saraswati/pull/14.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hiveeyes/saraswati/pull/14

-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

**Comment by MKO1640** [comment]
I think I could do that.
But I would like to point out that we should then support all codec-container combinations.
wav ; flac ; wav-ogg ; flac-ogg ; wav-mka ; flac-mka
I would then make available wav in connection with the ogg and wav containers.
Your suggestion requires a little more juggling, of course, when assembling the pipeline_expression string and that of the suffix as well.

I think we should close this pull request and I'll create a new one when I'm ready.

**Comment by MKO1640** [comment]
before I start to test and do a new pull request.
Did you imagine it to be like this?
https://github.com/MKO1640/saraswati/tree/dev-MKO1640

Unfortunately i have not yet found a solution to bring this to my test system quickly and easily.

**Comment by amotl** [comment]
Hi @MKO1640,

your patch looks excellent. Just submit a PR and I will add some comments to it.

With kind regards,
Andreas.

P.S.: You can `pip install` a Python package directly from a repository on GitHub like
```
pip install git+https://github.com/user/repo.git@branch
```
For testing purposes, you might want to install it into a virtualenv which can be completely removed afterwards, like
```
# Install
python3 -m venv --system-site-packages .venv
source .venv/bin/activate
pip install git+https://github.com/MKO1640/saraswati.git@dev-MKO1640

# Evaluate
saraswati record ....

# Clean up
deactivate
rm -r .venv
```

**Comment by MKO1640** [comment]
I had tried before. think i have to look again for git.

```
user@Hiveeyes01:~$ pip install git+https://github.com/MKO1640/saraswati.git@dev-MKO1640
Collecting git+https://github.com/MKO1640/saraswati.git@dev-MKO1640
  Cloning https://github.com/MKO1640/saraswati.git (to revision dev-MKO1640) to /tmp/pip-req-build-skdelskr
  Running command git clone -q https://github.com/MKO1640/saraswati.git /tmp/pip-req-build-skdelskr
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/MKO1640/saraswati.git /tmp/pip-req-build-skdelskr
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

**Comment by amotl** [comment]
Hm. Are you sure `git` is installed on your system? `apt-get install git` might help...

**Comment by MKO1640** [comment]
I believed that linux mint git is installed by default.
I installed it, now it works.

**Comment by amotl** [comment]
Closing this in favor of #15.

**Pull request closed without merging**
